/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  css: ["@/app/globals.css"],
  css: ["@/app/custom.css"],
  css: ["@/app/responsive.css"],
  swcMinify: false,
  images: {
    domains: [
      "cdn-icons-png.flaticon.com",
      "www.franchisezing.com",
      "i.pinimg.com",
      "rukminim2.flixcart.com",
      "1000logos.net",
      "www.marksandspencer.in",
      "mothersparsh.com",
      "www.peesafe.com",
      "media-ik.croma.com",
      "cdn.grabon.in",
      "supertails.com",
      "api.cashdost.com",
      "plumgoodness.com",
      "dspncdn.com",
      "i.ytimg.com",
      "media.istockphoto.com",
      "www.aldoshoes.in",
      "encrypted-tbn0.gstatic.com",
      "www.offeraty.com",
      "www.dominos.co.in",
      "img6.hkrtcdn.com",
      "images-loyalty.ovo.id",
      "img8.hkrtcdn.com",
      "m.media-amazon.com",
      "brand.assets.adidas.com",
      "www.bombayshavingcompany.com",
      "cdn.shopify.com",
      "www.lenovo.com",
      "5.imimg.com",
      "www.blog.cashdost.com",
      "etimg.etb2bimg.com",
      "upload.wikimedia.org",
    ],
  },
  trailingSlash: true,
};

module.exports = nextConfig;
